### ISSUE TITLE
Optimize CFF's defaultWidthX and nominalWidthX values

### ISSUE THREAD

**Issue by miguelsousa** [typesupply/ufo2fdk#34]
Currently the default values for `defaultWidthX` and `nominalWidthX` are [200 and 0](https://github.com/typesupply/ufo2fdk/blob/master/Lib/ufo2fdk/fontInfoData.py#L420-L421) and they are never adjusted according to the glyphs in the font. This makes for a slightly bigger CFF table when compared with what **makeotf** produces.

[otf-making-benchmark](https://github.com/adobe-type-tools/otf-making-benchmark) has two test cases.

**Comment by miguelsousa** [comment]
@typemytype It's in [recode.c](https://github.com/adobe-type-tools/afdko/blob/master/afdko/Tools/Programs/makeotf/makeotf_lib/source/typecomp/recode.c#L97-L125) I believe.

Here's what @readroberts said when I asked him to explain to me how it works:

> The process is iterative, as the choices interact . To quote from recode.c:
>"The first is that the choice of nominal width and default width interact. For example, choosing a nominal width near a default width will make the potential default width savings smaller. The second is that the optimal choice of nominal width can make some encoded widths larger."
>
>1. Calculate the size of char strings widths without optimization (e.g default width X= 0). For each glyph width, calculate the total width savings with nominal width X = cur glyph with, and all possible default widths:
>* For each glyph:
>	* Set total nominal width size = 0
>	* Current nominal glyph width = glyph width
>* For each glyph:
>	* Set total nominal width size = total nominal width size + byte size of (glyph width - Current nominal glyph width)
>
>2. Now try using each glyph width in turn as a possible value for default width, and calculating the total width size. Every time the total width size is smaller than the saved best size, save the current nominal width choice and default width choice.
>* For each glyph:
>	* Set default width to width of glyph.
>	* Total width size = byte size of (total nominal width size - default width) * number of glyphs with the default width.
>	* If Total width size is less than best total width size, save the current nominal and default width choices.
>
>3. If the best total width size is larger than the size of char strings widths without optimization, then set default width X= 0 ( no optimization), else save the best nominal and default width choices.
>
> The code is a bit more complicated than this because the size of the width values is the size of the Type 2 token for the numeric value, which takes some calculation.

/cc @behdad @anthrotype

**Comment by behdad** [comment]
Thanks Miguel. I'm surprised this was actually implemented there. :)

It sounds like its doing an exhaustive search. Which, indeed, results in absolute optimal solution.  We can implement that in a simpler way however. I'll sketch it soon.  The input to the procedure is a dictionary mapping glyph widths to their frequency (number of times occurring). The output is nominal and default widths. It makes for a very nice problem.  I'll think about it.  It's even possible to implement the brute-force approach and an optimized version which should then match the bruteforce for all inputs.

**Comment by behdad** [comment]
This should have been filed against ufo2ft / fonttools.  I have an implementation in fonttools now. Needs to be hooked up to ufo2ft.

**Comment by miguelsousa** [comment]
@behdad it was https://github.com/googlei18n/ufo2ft/issues/216

**Comment by behdad** [comment]
Here's my code: https://github.com/fonttools/fonttools/commit/a70bca61fe8d89b355737e17335fd3a0d6bfaf5c#diff-26e31be1fca6b1254b2aa48483df0810R92

**Comment by typemytype** [comment]
thanks @behdad waiting until width.py is py3 compatible to merge it

https://github.com/typesupply/ufo2fdk/pull/35

**Comment by behdad** [comment]
Fixed it yesterday.

**Comment by typemytype** [comment]
mmm, Im overseeing something (I dont see the fix..): https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/cffLib/width.py

or its fixed in a branch somewhere...

**Comment by behdad** [comment]
> or its fixed in a branch somewhere...

Humm. Donno what happened. Fixed now. Please check.

**Comment by typemytype** [comment]
thanks!!

**Comment by behdad** [comment]
Someone still needs to hook it up in ufo2fdk if that's desirable.  But doesn't ufo2fdk use makeotf anyway? Not sure why this is filed here.

**Comment by miguelsousa** [comment]
Frederik already hooked it up to **ufo2fdk**. It still needs to be hooked up to **ufo2ft**. The latter is a fork of the former. I'm under the impression that ufo2fdk does not depend on makeotf as much as it used to. In case I'm wrong this change in ufo2fdk is indeed unnecessary because the values will be recalculated by makeotf.

**Comment by typemytype** [comment]
Ive implemented this to improve the font info fallbacks.
